config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :photos
  resources :albums
  resources :portraits
  resources :interiors
  resources :articles
  resources :start
  resources :imagesliders
  resources :contact_forms

  get '*path' => redirect('/')

  root 'albums#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_attached_file :document, styles: {thumbnail: "60x60#"}
  validates_attachment :document, content_type: { content_type: "application/pdf" }
  mount_uploader :paper, PaperUploader
  mount_uploader :picture, PictureUploader

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/interior.rb
class Interior < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :album
  belongs_to :interior
  belongs_to :portrait
end

app/models/portrait.rb
class Portrait < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  mount_uploader :profile_picture, PictureUploader
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/interiors_helper.rb
module InteriorsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  class ClassMethods
    def self.which_tpye_of_album(photo)
       if !photo.album.nil?
         return "album"
       elsif !photo.interior.nil?
         return "interior"
       elsif !photo.portrait.nil?
         return "portrait"
       else
          return "no relation"
       end
    end
    def self.get_ablum(modal, photo)
      if modal == "album"
        puts"haj"
        album = Album.find(photo.album_id)
        album_ordered = album.photos.order("CASE WHEN id = '#{photo.id}' THEN 1 ELSE 2 END, id")
        return album_ordered
      elsif modal == "interior"
        interior = Interior.find(photo.interior_id)
        return interior.photos.order("CASE WHEN id = '#{photo.id}' THEN 1 ELSE 2 END, id")
      elsif modal == "portrait"
        portrait = Portrait.find(photo.portrait_id)
        return portrait.photos.order("CASE WHEN id = '#{photo.id}' THEN 1 ELSE 2 END, id")
      else
        puts"haj"
         return "no relation"
      end
    end
  end
end

app/helpers/portraits_helper.rb
module PortraitsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Julia</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/header"%>
  <%= yield %>

</body>
</html>

app/views/shared/_header.html.erb
<%unless @navbar_hidden%>
  <div class="portfolio-nav">
    <!-- <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
        </ul>
      </div>
    </div>
  </nav> -->
    <div class="container">
      <div class="row">
        <div class="col-md-4 name-col">
          <div class="pull-left">
            <%=link_to(start_index_path) do%>
              <h1><strong>Julia Grufving</strong></h1>
            <%end%>
          </div>
        </div>
        <div class="col-md-8 portfolio-nav">
          <nav class="navbar navbar-default navbar-left" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-left">
                <li><%=link_to 'Travel', albums_path%>
                  </li>
                <li><%=link_to 'Portraits', portraits_path%></li>
                <li><%=link_to 'Interior', interiors_path%></li>
                <li>
                  <%=link_to 'Articles', articles_path%>
                </li>
                <li>
                  <%=link_to 'Contact', contact_forms_path%>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/shared/_render_articles.html.erb
<div class="col-md-3 col-lg-3 col-xs-6 col-sm-6">
    <div class="article-picture">
      <%=link_to(article.paper.url) do %>
        <%=image_tag(article.paper.normal_white, class:"img-responsive")%>
      <%end%>
    </div>
      <div class="header-text">
        <%=link_to(article.paper.url) do %>
          <h2><%=article.name%></h2>
        <%end%>
      </div>
</div>