config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :photos
  resources :albums
  resources :portraits
  resources :interiors
  resources :articles
  resources :start
  resources :imagesliders
  resources :contact_forms

  get '*path' => redirect('/')

  root 'albums#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_attached_file :document, styles: {thumbnail: "60x60#"}
  validates_attachment :document, content_type: { content_type: "application/pdf" }
  mount_uploader :paper, PaperUploader
  mount_uploader :picture, PictureUploader

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/interior.rb
class Interior < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :album
  belongs_to :interior
  belongs_to :portrait
end

app/models/portrait.rb
class Portrait < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  mount_uploader :profile_picture, PictureUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end
  def show
    @album = Album.find(params[:id])
    @photos = @album.photos.all
    puts "@photos", @photos
  end
  def new
    @album = Album.new
  end
  def create
    @album = Album.new(album_params)
    puts "aa", @album
    if @album.save
      redirect_to @album
    else
      render 'new'
    end
  end
  private
    def album_params
      params.require(:album).premit(:name)
    end
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
    # @potrait_photo = Photo.where(picture: "frontbild.jpg");
    # @cover_photo = Photo.where(picture: "frontcoover.jpg");
    @profile = Profile.last
    if @profile == nil
      
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/imagesliders_helper.rb
module ImageslidersHelper
end

app/helpers/interiors_helper.rb
module InteriorsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  class ClassMethods
    def self.which_tpye_of_album(photo)
       if !photo.album.nil?
         return "album"
       elsif !photo.interior.nil?
         return "interior"
       elsif !photo.portrait.nil?
         return "portrait"
       else
          return "no relation"
       end
    end
    def self.get_ablum(modal, photo)
      if modal == "album"
        puts"haj"
        album = Album.find(photo.album_id)
        album_ordered = album.photos.order("CASE WHEN id = '#{photo.id}' THEN 1 ELSE 2 END, id")
        return album_ordered
      elsif modal == "interior"
        interior = Interior.find(photo.interior_id)
        return interior.photos.order("CASE WHEN id = '#{photo.id}' THEN 1 ELSE 2 END, id")
      elsif modal == "portrait"
        portrait = Portrait.find(photo.portrait_id)
        return portrait.photos.order("CASE WHEN id = '#{photo.id}' THEN 1 ELSE 2 END, id")
      else
        puts"haj"
         return "no relation"
      end
    end
  end
end

app/helpers/portraits_helper.rb
module PortraitsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/albums/_render_album_view.html.erb
<%if index < 1%>
<div class="col span_4_of_10">
  <div class="hovereffect">
      <%=link_to album_path(album) do %>
        <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
        <div class="overlay">
            <h2><%=album.name%></h2>
        </div>
      <%end%>
  </div>
</div>
<%elsif index >= 1 and index < 2%>
  <div class="col span_6_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index >= 2 and index < 3 %>
  <div class="col span_6_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index >= 3 and index < 4%>
  <div class="col span_4_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index >= 4 and index < 5%>

  <div class="col span_5_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index  >= 5 and index < 6%>
  <div class="col span_5_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index  >=6%>
  <%index = 0%>
  <%= render partial: 'render_normal_view', locals: {album: album, index: index} %>
<%end%>

app/views/albums/_render_normal_view.html.erb
<%if index < 1%>
<div class="album-bootstrap-col">
  <div class="col-md-4 col-sm-4 col-lg-4 col-xs-12">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
</div>
<%elsif index >= 1 and index < 2%>
  <div class="col span_6_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index >= 2 and index < 3 %>
  <div class="col span_6_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index >= 3 and index < 4%>
  <div class="col span_4_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index >= 4 and index < 5%>

  <div class="col span_5_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index  >= 5 and index < 6%>
  <div class="col span_5_of_10">
    <div class="hovereffect">
        <%=link_to album_path(album) do %>
          <%=image_tag(album.photos.first.picture.normal_thumb, class:"img-responsive")%>
          <div class="overlay">
              <h2><%=album.name%></h2>
          </div>
        <%end%>
    </div>
  </div>
<%elsif index  >=6%>
  <%index = 0%>
  <%= render partial: 'render_normal_view', locals: {album: album, index: index} %>
<%end%>

<%index += 1%>

app/views/albums/index.html.erb
<div id="new-album-view">
  <div class="container">
    <div class="center-pictures">
        <div class="section group">
          <% number = 0 %>
            <%@albums.each_with_index do |album,index|%>
              <%if !album.photos.first.nil? %>
                <%= render partial: 'render_album_view', locals: {album: album, index: number} %>
                <% number += 1 %>
              <%end%>
            <%end%>
          </div>
        </div>
      </div>
    </div>

app/views/albums/show.html.erb
<script>
$(document).ready(function(){
  var fullscreen = 1200;
  var tablet_screen = 990;
  var mobile_screen = 770;

  $(window).resize(function() {
    console.log($(window).width());
    if($(window).width() > fullscreen){
      $("<%# @full_screen = true %>");

      console.log("inresize?" + "<%#= @full_screen %>");
      // location.reload();
    }
    if($(window).width() > tablet_screen && $(window).width() < fullscreen){
      console.log("hejjejej")
      console.log("hej" + "<%# @full_screen = false %>");
      // location.reload();
    }

  });
});

</script>

<div id="show-pictures">

  <div class="jumbotron">
    <div class="container">
      <div class="center-pictures">
        <div class="section group">
            <%number=0%>
            <%@photos.each do |photo|%>
                <%if number < 1%>
                    <div class="col span_2_of_7">
                      <%=link_to(photo_path(photo)) do%>
                        <%=image_tag(photo.picture.normal_thumb, class:"img-responsive")%>
                      <%end%>
                    </div>
                <%elsif number >= 1 and number < 2%>
                    <div class="col span_2_of_7">
                      <%=link_to(photo_path(photo)) do%>
                        <%=image_tag(photo.picture.normal_thumb, class:"img-responsive")%>
                      <%end%>
                    </div>
                <%elsif number >= 2 and number < 3 %>
                    <div class="col span_3_of_7">
                      <%=link_to(photo_path(photo)) do%>
                        <%=image_tag(photo.picture.normal_thumb, class:"img-responsive")%>
                      <%end%>
                    </div>

                <%elsif number  >= 3 and number < 4%>
                    <div class="col span_2_of_7">
                        <%=link_to(photo_path(photo)) do%>
                          <%=image_tag(photo.picture.normal_thumb, class:"img-responsive")%>
                        <%end%>
                    </div>
                <%elsif number  >= 4 and number < 5%>

                    <div class="col span_3_of_7">
                      <%=link_to(photo_path(photo)) do%>
                          <%=image_tag(photo.picture.normal_thumb, class:"img-responsive")%>
                      <%end%>
                    </div>

                <%elsif number  >= 5 and number < 6%>

                    <div class="col span_2_of_7">
                      <%=link_to(photo_path(photo)) do%>
                        <%=image_tag(photo.picture.normal_thumb, class:"img-responsive ")%>
                      <%end%>
                    </div>
                <%elsif number  >= 6 and number < 7%>
                    <%number = 0%>
                    <div class="col span_2_of_7">
                      <%=link_to(photo_path(photo)) do%>
                        <%=image_tag(photo.picture.normal_thumb, class:"img-responsive ")%>
                      <%end%>
                    </div>
                <%end%>
                <%number += 1%>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>